### PR TITLE
Add common.js tests for message preferences coverage

### PR DESCRIPTION
**Pull request by WesTyler**
100% coverage on `lib/messages.js`, slight improvements in `/lib/errors.js` and `/lib/template.js` as a bonus :).

The test added to the `test/types/any.js` is technically redundant, but I thought was a good addition from a "tests as documentation" perspective.

### CODE REVIEW

**Comment by WesTyler** [comment]
I resolved the merge conflicts. I know there are a silly number of commits in this PR, I planned on squashing if/when this got approved :)

**Comment by cjihrig** [comment]
Hm, for some reason I'm not seeing the CI run here?

**Comment by WesTyler** [comment]
Oh that's weird... Should I close this PR and reopen to try to kick-start it?

**Comment by cjihrig** [comment]
I'd try squashing and force pushing this branch. I'm not sure if the merge commit causes any issues with Travis or not, but getting rid of merge commits is never a bad idea.

**Comment by WesTyler** [comment]
I totally made a mess of the squashed merge commit. Going to clean up my mess and re-open

**Comment by WesTyler** [comment]
Fixed with https://github.com/hapijs/validate/pull/4

**Pull request closed without merging**
