### PR TITLE
100% coverage on lib/messages.js

### PR DESCRIPTION
**Pull request by WesTyler**
100% test coverage on /lib/messages.js.

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]
LGTM at a quick glance.

cc @devinivy who has been more in the weeds here.

**Review by devinivy — APPROVED** [review]
This looks great, thanks a lot!

**Comment by WesTyler** [comment]
Thanks gents :)

**Comment by cjihrig** [comment]
No, thank YOU 😄

**Pull request merged**
